### ISSUE TITLE
[nodemon] clean exit - waiting for changes before restart

### ISSUE THREAD

**Issue by jebuskhoury** [milktoastlab/SolanaNFTBot#14]
Hey, Im getting this message everytime I try to run `yarn dev`command, Did I do anything wrong ?
I changed before the package.json from:
`"ts-run": "PORT=4000 ts-node src/server.ts"`
to
`"ts-run": "SET PORT=4000 ts-node src/server.ts"`

**Comment by kryptoj** [comment]
@jebuskhoury Can you show the logs/error that you see when running `yarn dev`?

**Comment by kryptoj** [comment]
FYI In the latest version I have removed the hardcoded PORT. Not sure if it helps with your issue.
