### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by ArtemAlagizov** [milktoastlab/SolanaNFTBot#15]
hey, thanks for the bot!

don't seem to be able to run it, though:
* platform - AWS Linux based AMZN2 image
  ```bash
  #  cat /etc/os-release
  NAME="Amazon Linux"
  VERSION="2"
  ID="amzn"
  ID_LIKE="centos rhel fedora"
  VERSION_ID="2"
  PRETTY_NAME="Amazon Linux 2"
  ANSI_COLOR="0;33"
  CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
  HOME_URL="https://amazonlinux.com/"
  ```
* docker version - 20.10.7
  ```bash
  # docker version
  Client:
   Version:           20.10.7
   API version:       1.41
   Go version:        go1.15.14
   Git commit:        f0df350
   Built:             Wed Nov 17 03:05:36 2021
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server:
   Engine:
    Version:          20.10.7
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.15.14
    Git commit:       b0f5bc3
    Built:            Wed Nov 17 03:06:14 2021
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.4.6
    GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
   runc:
    Version:          1.0.0
    GitCommit:        84113eef6fc27af1b01b3181f31bbaf708715301
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  ```
* docker run command
  ```bash
  docker run --name nftbot -d -p 4000:4000 -e DISCORD_BOT_TOKEN=xxx -e SUBSCRIPTION_DISCORD_CHANNEL_ID=xxx -e SUBSCRIPTION_MINT_ADDRESS=xxx milktoastlab/solananftbot
  ```
* what happens:
  * container runs and exists immediately 
  * when run command is executed a warning is displayed
    ```bash
    WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
    ```
  * logs from the stopped container
    ```bash
    standard_init_linux.go:228: exec user process caused: exec format error
    ```
* also tried specifying "--platform linux/arm64/v8"
  ```bash
  docker run --name nftbot -d --platform linux/arm64/v8 -p 4000:4000 -e DISCORD_BOT_TOKEN=xxx -e SUBSCRIPTION_DISCORD_CHANNEL_ID=xxx -e SUBSCRIPTION_MINT_ADDRESS=xxx milktoastlab/solananftbot
  ```
  * runs the container without the warning, but it also exits soon after launching, when checking logs, only this line is in the logs
    ```bash
    standard_init_linux.go:228: exec user process caused: exec format error
    ```

would appreciate any help!

**Comment by ArtemAlagizov** [comment]
alright, it has to do with the way the image is built - i just built it myself (on linux 20) and it works now.
so, it's about architecture, i reckon, was the image built on a MAC?

**Comment by kryptoj** [comment]
@ArtemAlagizov Interesting. It was built on a MAC.

**Comment by kryptoj** [comment]
It's a good find. Will look into building cross-platform docker images.

**Comment by ArtemAlagizov** [comment]
alright!
well, the issue is solved for me (by building the docker image locally using your source code), so feel free to close the issue when you think it is solved.
and the bot works great, thanks again!

**Comment by kryptoj** [comment]
The official docker image should support linux/amd64. 
https://hub.docker.com/r/milktoastlab/solananftbot/tags

<img width="861" alt="Screen Shot 2021-12-09 at 11 45 23 pm" src="https://user-images.githubusercontent.com/90617759/145398961-655602cf-df99-4283-9111-8b14eba8c384.png">
