### ISSUE TITLE
Help! please

### ISSUE THREAD

**Issue by funkzzz** [milktoastlab/SolanaNFTBot#49]
Does anyone know how to make this a hyperlink to the buyer/seller account? Like I want it to navigate to https://magiceden.io/u/{nft Sale.buyer/seller}
But I don't know how to do it here is the code:
![image](https://user-images.githubusercontent.com/98845419/194896735-88005ba6-17bc-47b3-98ec-c6e010c2445b.png)
![image](https://user-images.githubusercontent.com/98845419/194896849-d6547495-d7e9-4c1e-88fb-23446c6d49e9.png)
https://github.com/milktoastlab/SolanaNFTBot/blob/main/src/lib/discord/notifyDiscordSale.ts#L82

**Comment by funkzzz** [comment]
this is the line on the code if needed https://github.com/milktoastlab/SolanaNFTBot/blob/main/src/lib/discord/notifyDiscordSale.ts#L82

**Comment by kryptoj** [comment]
@funkzzz you can try the masked link example in this article for put links in the field value: https://anidiots.guide/first-bot/using-embeds-in-messages/

**Comment by funkzzz** [comment]
Thank you very much and could I maybe have a little more help? I want to make the bot Custom status. ( WATCHING , 'Github')

**Comment by funkzzz** [comment]
Thank you very much you are the best!
