### ISSUE TITLE
Magic Eden sales tracking

### ISSUE THREAD

**Issue by lminor** [milktoastlab/SolanaNFTBot#55]
It looks like there is an issue reading sales now that Magic Eden has swapped the sales contract. 

From MetaHelix Discord - Update regarding ME sales tracking:

Magic Eden have changed their NFT Sale contract over the weekend, making it so our tracking bots are temporarily not able to collect sales data for these collections. The technical reason is that  the sale contract no longer lists all creators in the transactions, including the verified creator of the collection, which is the wallet we track to collect this data.

There are a few different work arounds we are currently looking at in order to fix this, and will give you all an update regarding that soon.

**Comment by b4rtt** [comment]
Hey, did you find any way to solve this? I haven't found a way to fix it yet.

**Comment by lminor** [comment]
@b4rtt nothing yet. I have debugged a bit but it looks like the parsed transactions from Magic Eden now don't contain the correct data to be classified as a sale. The odd thing is I haven't been able to get the info I am expecting from their updated transactions so I can't debug it yet. Thinking that there is a secondary call that needs to happen when its Magic Eden to just grab the data.

@kryptoj any thoughts?

**Comment by kryptoj** [comment]
@lminor do you have links to the sales transactions that are not working?

**Comment by kryptoj** [comment]
MagicEden has changed its Program before, we're able to fix it by adding a new program (address) to the list. https://github.com/milktoastlab/SolanaNFTBot/blob/main/src/lib/marketplaces/magicEden.ts#L6-L9

**Comment by kryptoj** [comment]
>Magic Eden have changed their NFT Sale contract over the weekend, making it, so our tracking bots are temporarily not able to collect sales data for these collections. The technical reason is that the sale contract no longer lists all creators in the transactions, including the verified creator of the collection, which is the wallet we track to collect this data.

That does sound like it could be harder to fix.

**Comment by kryptoj** [comment]
Added support for MagicEden's V2 in the latest version. See https://github.com/milktoastlab/SolanaNFTBot#magic-eden-variables for more details.
